name: Test Builds
on:
  # run for all pull requests
  # Run for all commits on feature branches
  push:
  pull_request:
jobs:
  ###############################################################################
  # builds the application on windows
  testBuildWindows:
    runs-on: windows-latest

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.19.x'

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure
      run: |
        cmake.exe -G "Visual Studio 16 2019" -A x64 -B build

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: VCOTuner_Windows
        path: build\VCOTuner_artefacts\Release\VCOTuner.exe

  ###############################################################################
  # builds the application on macos
  testBuildMacOS:
    runs-on: macos-latest

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.19.x'

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure
      run: |
        cmake -G "Xcode" -B build -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: VCOTuner_MacOS
        path: build/VCOTuner_artefacts/Release/**

  ###############################################################################
  # builds the application on ubuntu
  testBuildUbuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.19.x'

    - name: Setup dependencies
      run: |
        sudo apt-get -y install g++ libfreetype6-dev libx11-dev libxinerama-dev libxrandr-dev libxcursor-dev mesa-common-dev libasound2-dev freeglut3-dev libxcomposite-dev

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure
      run: |
        cmake -G "Unix Makefiles" -B build

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: VCOTuner_Linux
        path: build/VCOTuner_artefacts/VCOTuner


